### ISSUE TITLE
feat/source: Add NetSuite & NetSuite2 sources

### ISSUE THREAD

**Issue by hieumdd** [vuanembi/vuanem-dbt#1]

**Comment by hoainam2611** [comment]
**IP_SuiteAnalyticsConnect**

select 
  distinct 
  -- table_schema, 
  table_name,  
  -- table_type
from `IP_SuiteAnalyticsConnect.INFORMATION_SCHEMA.TABLES`
where 1=1 
order by table_name 

table_name
ACCOUNTING_PERIODS
ACCOUNTS
ADDRESS
ADDRESS_BOOK
BUDGET
CAMPAIGNS
CASES
CASE_TYPES
CITYPROVINCE_LIST
CLASSES
CUSTOMERS
DELIVERY_METHOD
DELIVERY_PERSON
DEPARTMENTS
EMPLOYEES
ENTITY
IR
ITEMS
ITEM_LOCATION_MAP
ITEM_VENDOR_MAP
LOCATIONS
LOYALTY_CUSTOMER_GROUP
LOYALTY_POINT
LOYALTY_TRANSACTION
ORDER_PAYMENT_METHOD
ORIGINATING_LEADS
PROMOTION_SMS_INTEGRATION
PURCHASE_ORDER
QUANHUYEN_LIST
RATING
SERVICE_ADDON_SO_MAP
SERVICE_ADDON_TO_MAP
STORE_TRAFFIC
SUBSIDIARIES
SUBSIDIARY_LOCATION_MAP
SUPPORT_PERSON_MAP
SYSTEM_NOTES_BILLED
SYSTEM_NOTES_CHANGE
SYSTEM_NOTES_CREATE
SYSTEM_NOTES_PRICE
SYSTEM_NOTES_SUCCESS
SYSTEM_NOTES_SUCCESSFUL
TRANSACTIONS_20180101
TRANSACTIONS_20180701
TRANSACTIONS_20190101
TRANSACTIONS_20190701
TRANSACTIONS_20200101
TRANSACTIONS_20200701
TRANSACTIONS_20210101
TRANSACTIONS_20210701
TRANSACTIONS_20220101
TRANSACTIONS_20220701
TRANSACTIONS_20230101
TRANSACTIONS_20230701
TRANSACTION_LINES_20180101
TRANSACTION_LINES_20180701
TRANSACTION_LINES_20190101
TRANSACTION_LINES_20190701
TRANSACTION_LINES_20200101
TRANSACTION_LINES_20200701
TRANSACTION_LINES_20210101
TRANSACTION_LINES_20210701
TRANSACTION_LINES_20220101
TRANSACTION_LINES_20220701
TRANSACTION_LINES_20230101
TRANSACTION_LINES_20230701
UNITS_TYPE
VENDORS
classification
couponcode
delivery_method
delivery_time
department
employee
expected_shipping_method
leadsource
location
order_payment_method
partner
profit_and_loss
promotioncode
sa_sales
sales_2
sales_order
subsidiary
vendor

**IP_SuiteAnalyticsConnect2**

select 
  distinct 
  -- table_schema, 
  table_name,  
  -- table_type
from `IP_SuiteAnalyticsConnect2.INFORMATION_SCHEMA.TABLES`
where 1=1 
order by table_name 

table_name
account
budget
classification
couponcode
delivery_method
delivery_time
department
employee
expected_shipping_method
item
leadsource
location
order_payment_method
partner
promotioncode
store_traffic
subsidiary
tranpromotion
transaction_20180101
transaction_20180701
transaction_20190101
transaction_20190701
transaction_20200101
transaction_20200701
transaction_20210101
transaction_20210701
transaction_20220101
transaction_20220701
transaction_20230101
transaction_20230701
transactionaccountingline_20180101
transactionaccountingline_20180701
transactionaccountingline_20190101
transactionaccountingline_20190701
transactionaccountingline_20200101
transactionaccountingline_20200701
transactionaccountingline_20210101
transactionaccountingline_20210701
transactionaccountingline_20220101
transactionaccountingline_20220701
transactionaccountingline_20230101
transactionaccountingline_20230701
transactionline_20180101
transactionline_20180701
transactionline_20190101
transactionline_20190701
transactionline_20200101
transactionline_20200701
transactionline_20210101
transactionline_20210701
transactionline_20220101
transactionline_20220701
transactionline_20230101
transactionline_20230701
vendor
